// <auto-generated />
#nullable enable

namespace EcoRoot.Resources;

using System;
using System.Globalization;
using System.Resources;

public static class Strings
{
    static ResourceManager? resourceManager;
    static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager
    {
        get
        {
            resourceManager ??= new ResourceManager("EcoRoot.Resources.Strings", typeof(Strings).Assembly);
            return resourceManager;
        }
    }

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    static string Get(string name) => ResourceManager.GetString(name, resourceCulture) ?? string.Empty;

    public static string AppTitle => Get("AppTitle");
    public static string HomeTitle => Get("HomeTitle");
    public static string HomeHeadline => Get("HomeHeadline");
    public static string HomeSubtitle => Get("HomeSubtitle");
    public static string HomeFocusTitle => Get("HomeFocusTitle");
    public static string HomeFocusDescription => Get("HomeFocusDescription");
    public static string HintOpenFoundations => Get("HintOpenFoundations");
    public static string HomeProgressTitle => Get("HomeProgressTitle");
    public static string HomePillarsTitle => Get("HomePillarsTitle");
    public static string HomeTeacherCornerTitle => Get("HomeTeacherCornerTitle");
    public static string HomeTeacherCornerBody => Get("HomeTeacherCornerBody");
    public static string HintOpenTeacherResources => Get("HintOpenTeacherResources");
    public static string HomePrimaryAction => Get("HomePrimaryAction");
    public static string HomeSecondaryAction => Get("HomeSecondaryAction");
    public static string HintOpenGlossary => Get("HintOpenGlossary");
    public static string HomeTeacherResourcesAction => Get("HomeTeacherResourcesAction");
    public static string HomeProgressEmpty => Get("HomeProgressEmpty");
    public static string HomeProgressFormat => Get("HomeProgressFormat");
    public static string ModulesTitle => Get("ModulesTitle");
    public static string ModulesHeading => Get("ModulesHeading");
    public static string ModulesSubtitle => Get("ModulesSubtitle");
    public static string ModulesEmpty => Get("ModulesEmpty");
    public static string ModulesViewLessons => Get("ModulesViewLessons");
    public static string HintOpenModuleLessons => Get("HintOpenModuleLessons");
    public static string LessonsTitle => Get("LessonsTitle");
    public static string LessonsEmpty => Get("LessonsEmpty");
    public static string OpenLesson => Get("OpenLesson");
    public static string HintOpenLessonDetails => Get("HintOpenLessonDetails");
    public static string LessonSectionsTitle => Get("LessonSectionsTitle");
    public static string QuizCheckUnderstandingTitle => Get("QuizCheckUnderstandingTitle");
    public static string HintStartQuiz => Get("HintStartQuiz");
    public static string QuizCheckAnswer => Get("QuizCheckAnswer");
    public static string QuizCheckAnswerHint => Get("QuizCheckAnswerHint");
    public static string QuizNextQuestion => Get("QuizNextQuestion");
    public static string QuizNextQuestionHint => Get("QuizNextQuestionHint");
    public static string QuizFinish => Get("QuizFinish");
    public static string GlossaryTitle => Get("GlossaryTitle");
    public static string GlossaryIntro => Get("GlossaryIntro");
    public static string GlossaryEmpty => Get("GlossaryEmpty");
    public static string GlossaryTermSoilContamination => Get("GlossaryTermSoilContamination");
    public static string GlossaryTermHeavyMetals => Get("GlossaryTermHeavyMetals");
    public static string GlossaryTermPesticideResidue => Get("GlossaryTermPesticideResidue");
    public static string GlossaryTermLeaching => Get("GlossaryTermLeaching");
    public static string GlossaryTermRemediation => Get("GlossaryTermRemediation");
    public static string GlossaryTermBioaccumulation => Get("GlossaryTermBioaccumulation");
    public static string ActivityTitle => Get("ActivityTitle");
    public static string ActivitySubtitle => Get("ActivitySubtitle");
    public static string ActivityAction => Get("ActivityAction");
    public static string ActivityHint => Get("ActivityHint");
    public static string ActivityNextScenario => Get("ActivityNextScenario");
    public static string ActivityNextScenarioHint => Get("ActivityNextScenarioHint");
    public static string SelectOptionHint => Get("SelectOptionHint");
    public static string ActivityEmpty => Get("ActivityEmpty");
    public static string ActivityScenarioTitle1 => Get("ActivityScenarioTitle1");
    public static string ActivityScenarioPrompt1 => Get("ActivityScenarioPrompt1");
    public static string ActivityScenarioOption1A => Get("ActivityScenarioOption1A");
    public static string ActivityScenarioOption1B => Get("ActivityScenarioOption1B");
    public static string ActivityScenarioOption1C => Get("ActivityScenarioOption1C");
    public static string ActivityScenarioFeedback1A => Get("ActivityScenarioFeedback1A");
    public static string ActivityScenarioFeedback1B => Get("ActivityScenarioFeedback1B");
    public static string ActivityScenarioFeedback1C => Get("ActivityScenarioFeedback1C");
    public static string ActivityScenarioTitle2 => Get("ActivityScenarioTitle2");
    public static string ActivityScenarioPrompt2 => Get("ActivityScenarioPrompt2");
    public static string ActivityScenarioOption2A => Get("ActivityScenarioOption2A");
    public static string ActivityScenarioOption2B => Get("ActivityScenarioOption2B");
    public static string ActivityScenarioOption2C => Get("ActivityScenarioOption2C");
    public static string ActivityScenarioFeedback2A => Get("ActivityScenarioFeedback2A");
    public static string ActivityScenarioFeedback2B => Get("ActivityScenarioFeedback2B");
    public static string ActivityScenarioFeedback2C => Get("ActivityScenarioFeedback2C");
    public static string ActivityScenarioTitle3 => Get("ActivityScenarioTitle3");
    public static string ActivityScenarioPrompt3 => Get("ActivityScenarioPrompt3");
    public static string ActivityScenarioOption3A => Get("ActivityScenarioOption3A");
    public static string ActivityScenarioOption3B => Get("ActivityScenarioOption3B");
    public static string ActivityScenarioOption3C => Get("ActivityScenarioOption3C");
    public static string ActivityScenarioFeedback3A => Get("ActivityScenarioFeedback3A");
    public static string ActivityScenarioFeedback3B => Get("ActivityScenarioFeedback3B");
    public static string ActivityScenarioFeedback3C => Get("ActivityScenarioFeedback3C");
    public static string ProgressTitle => Get("ProgressTitle");
    public static string ProgressStatsTitle => Get("ProgressStatsTitle");
    public static string ProgressHeadline => Get("ProgressHeadline");
    public static string ProgressBody => Get("ProgressBody");
    public static string ProgressBadgesTitle => Get("ProgressBadgesTitle");
    public static string ProgressQuizAttemptsTitle => Get("ProgressQuizAttemptsTitle");
    public static string ProgressQuizEmpty => Get("ProgressQuizEmpty");
    public static string CloudSyncCardTitle => Get("CloudSyncCardTitle");
    public static string CloudSyncCardBody => Get("CloudSyncCardBody");
    public static string CloudSyncOpenAction => Get("CloudSyncOpenAction");
    public static string CloudSyncHint => Get("CloudSyncHint");
    public static string CloudSyncTitle => Get("CloudSyncTitle");
    public static string CloudSyncIntro => Get("CloudSyncIntro");
    public static string CloudSyncStatusTitle => Get("CloudSyncStatusTitle");
    public static string CloudSyncToggleHint => Get("CloudSyncToggleHint");
    public static string CloudSyncLastSyncTitle => Get("CloudSyncLastSyncTitle");
    public static string CloudSyncLastSyncEmpty => Get("CloudSyncLastSyncEmpty");
    public static string CloudSyncLastSyncFormat => Get("CloudSyncLastSyncFormat");
    public static string CloudSyncEnabled => Get("CloudSyncEnabled");
    public static string CloudSyncDisabled => Get("CloudSyncDisabled");
    public static string CloudSyncDataTitle => Get("CloudSyncDataTitle");
    public static string CloudSyncDataItemProgress => Get("CloudSyncDataItemProgress");
    public static string CloudSyncDataItemQuizAttempts => Get("CloudSyncDataItemQuizAttempts");
    public static string CloudSyncDataItemLastSync => Get("CloudSyncDataItemLastSync");
    public static string CloudSyncConsentRequired => Get("CloudSyncConsentRequired");
    public static string CloudSyncConsentHint => Get("CloudSyncConsentHint");
    public static string CloudSyncProvideConsent => Get("CloudSyncProvideConsent");
    public static string TeacherResourcesTitle => Get("TeacherResourcesTitle");
    public static string TeacherResourcesIntro => Get("TeacherResourcesIntro");
    public static string TeacherResourcesCopyButton => Get("TeacherResourcesCopyButton");
    public static string TeacherResourcesCopyHint => Get("TeacherResourcesCopyHint");
    public static string TeacherResourcesCopied => Get("TeacherResourcesCopied");
    public static string TeacherResourcesCopyFailed => Get("TeacherResourcesCopyFailed");
    public static string Completed => Get("Completed");
    public static string NotCompleted => Get("NotCompleted");
    public static string BadgeUnlocked => Get("BadgeUnlocked");
    public static string BadgeLocked => Get("BadgeLocked");
    public static string ModuleProgressSummaryFormat => Get("ModuleProgressSummaryFormat");
    public static string QuizSummaryEmpty => Get("QuizSummaryEmpty");
    public static string QuizSummaryFormat => Get("QuizSummaryFormat");
    public static string QuizScoreEmpty => Get("QuizScoreEmpty");
    public static string QuizScoreFormat => Get("QuizScoreFormat");
    public static string BadgeFirstLessonTitle => Get("BadgeFirstLessonTitle");
    public static string BadgeFirstLessonDesc => Get("BadgeFirstLessonDesc");
    public static string BadgeQuizStarterTitle => Get("BadgeQuizStarterTitle");
    public static string BadgeQuizStarterDesc => Get("BadgeQuizStarterDesc");
    public static string BadgeModuleFinisherTitle => Get("BadgeModuleFinisherTitle");
    public static string BadgeModuleFinisherDesc => Get("BadgeModuleFinisherDesc");
    public static string BadgeQuizExplorerTitle => Get("BadgeQuizExplorerTitle");
    public static string BadgeQuizExplorerDesc => Get("BadgeQuizExplorerDesc");
    public static string BadgeSoilChampionTitle => Get("BadgeSoilChampionTitle");
    public static string BadgeSoilChampionDesc => Get("BadgeSoilChampionDesc");
}
